def BotoesECss()
    list = {
            :name_list => 'Teste Lista',
            :plus_header => '.TMI28E0KnYSK9p > .\\_2ZNy4w8Nfa58d1:nth-child(1) > .nch-icon',
            :criar_quadro_header => 'li:nth-child(1) .Puvhv7-oGbJGmR',
            :board_name => '.\\_23NUW98LaZfBpQ',
            :create_board => '.uj9Ovoj4USRUQz',
            :site => 'https://trello.com/',
            :login_google => '#googleButton > .label',
            :login_field_email =>'user',
            :login_field_password => 'password',
            :btn_login => 'login',
            :name_board_header => 'Teste Header',
            :name_board_body => 'Teste Body',
            :text_in_header_board => '/html/body/div[1]/div[2]/div[1]/div[2]/main/div[3]/div/div[1]/div[1]/div[2]/h1',
            :first_board_on_list => '//*[@id="content"]/div/div[2]/div/div/div/div/div[2]/div/div/div[3]/div[2]/ul/li[1]',
            :button_mais_board => '/html/body/div[1]/div[2]/div[1]/div[2]/main/div[3]/div/div[2]/div/div/div[2]/div/ul[1]/li[5]/a',
            :button_criar_body => '//*[@id="content"]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div[2]/ul/li/div',
            :click_any_board => '//div[@id=\'content\']/div/div[2]/div/div/div/div/div[2]/div/div/div[3]/div[2]/ul/li/a/div',
            :click_mais => '//*[@id="content"]/div/div[2]/div/div/div[2]/div/ul[1]/li[5]/a',
            :add_list_to_dashboard => '.placeholder',
            :dashboard_fill_list_name => '.list-name-input',
            :button_adicionar_cartao => '.nch-button',
            :button_adicionar_cartao2 => '.js-add-a-card',
            :dashboard_fill_card_name => '.list-card-composer-textarea',
            :name_card => 'Criar Card',
            :lorem_ipsum_Checkbox_name => 'Name Checkbox',
            :click_In_close => '//*[@id="chrome-container"]/div[4]/div/div[2]/div/div/div/input',
            :confirm_board => 'board-menu-header-title js-board-menu-title-text',
            :name_card2 => 'Criar Card2',
            :button_confirm_css => '.confirm',
            :click_send_name_checkbox => '.wide',
            :button_adicionar_cartao3 => '.js-add-another-card',
            :text_in_card => '.list-card-title js-card-name',
            :click_in_first_card => '.list-card-title',
            :fill_coments_css => '.current > p',
            :lorem_ipsum => 'Lorem ipsum lorem dos grandes vales',
            :fill_field_text => 'description-edit edit',
            :fill_coments_css2 => '.field',
            :button_confirm_comment_css => '.mod-submit-edit',
            :click_add_tag => '.js-edit-labels > .js-sidebar-action-text',
            :click_tag_verde => '.card-label-green',
            :click_escape_tag => '.pop-over-header-close-btn',
            :text_in_header_tag => ".card-detail-item-header",
            :comment_field => '//*[@id="chrome-container"]/div[3]/div/div/div/div[4]/div[2]/div/div/div[2]/div/div/div[2]/p',
            :click_in_checklist_field => '.js-add-checklist-menu > .js-sidebar-action-text',
            :fill_checkbox_name => 'id-checklist',
            :fill_checkbox_with_activity => '.focus-visible',
            :lorem_ipsum_Checkbox_activity => 'Atividade teste',
            :click_send_activity => '.editing > .checklist-add-controls > .nch-button',
            :click_in_checkbox => '.checklist:nth-child(1) .checklist-item:nth-child(1) > .checklist-item-checkbox',
            :search_in_card => '//*[@id="chrome-container"]/div[3]/div/div/div/div[4]/div[10]/div[1]/div[1]/div/h3',
            :click_to_shelve_a_card => '.js-archive-card > .js-sidebar-action-text',
            :click_to_delet_card => '.js-delete-card > .js-sidebar-action-text',
            :click_to_confirm_deleted => '.js-confirm',
            :click_to_open_menu_in_list => '.list-header-extras-menu',
            :click_to_exclud_list => '.js-close-list'
           }
end